number1=int(input("Enter number 1:"))
number2=int(input("Enter number 2:"))
print("[Today's multiplication]")
print(number1,"+",number2,"=",number1+number2)
print(number1,"-",number2,"=",number1-number2)
print(number1,"*",number2,"=",number1*number2)
print(number1,"//",number2,"=",number1//number2)
print(number1,"/",number2,"=",number1/number2)
